"""Frases de entrenamiento en español para el clasificador edge de intención."""
from __future__ import annotations

INTENCIONES = ["KPI", "exploracion", "comparacion", "detalle", "grafico", "exportacion", "aclaracion"]

DESCRIPCION_INTENCION = {
    "KPI": "Pide un indicador agregado (total, promedio, ranking).",
    "exploracion": "Explora el catálogo: qué tablas, columnas o datos existen.",
    "comparacion": "Contrasta dos o más entidades o periodos.",
    "detalle": "Pide el detalle fila a fila de un subconjunto.",
    "grafico": "Pide explícitamente una visualización.",
    "exportacion": "Pide descargar o exportar los datos.",
    "aclaracion": "La pregunta es ambigua o incompleta y necesita contexto.",
}

ENTRENAMIENTO: dict[str, list[str]] = {
    "KPI": [
        "cuál es el ingreso total del año",
        "dame las ventas por mes",
        "ventas por mes",
        "cuánto vendimos en 2025",
        "total de unidades vendidas por categoría",
        "margen bruto acumulado",
        "top 10 clientes por ingreso",
        "cuáles son los 5 productos con más ventas",
        "ticket promedio por canal",
        "cuántos clientes activos tenemos",
        "porcentaje de margen por región",
        "ingresos del último trimestre",
        "dame el roi de las campañas",
        "cuánto facturamos por canal de venta",
        "suma de ventas por región",
        "promedio de csat de soporte",
        "número de ventas del mes pasado",
        "ranking de productos por margen",
        "cuál es la tasa de conversión web",
        "ingreso por segmento de cliente",
        "cuanto vendimos por trimestre",
        "kpis principales de ventas",
        # Cortesía o saludo delante de una pregunta analítica real
        "hola puedes decirme el margen de categorias",
        "hola dame el ingreso por region",
        "buenos dias quisiera el total de ventas del mes",
        "por favor muestrame el margen por categoria",
        "me puedes decir cuanto vendimos por canal",
        "buenas tardes necesito el ticket promedio por segmento",
        "oye dime el top de productos por margen",
        "hola quisiera saber el roi de las campañas",
        # Errores de tipeo frecuentes
        "meargen por categoria",
        "vantas por mes",
        "ingrso total por region",
        "margn por producto",
        "tiket promedio por canal",
    ],
    "exploracion": [
        "qué tablas tengo disponibles",
        "muéstrame el catálogo de datos",
        "qué columnas tiene la tabla ventas",
        "qué información hay de clientes",
        "qué datos puedo consultar",
        "explícame el modelo de datos",
        "qué métricas existen",
        "listar tablas del warehouse",
        "qué tablas no relacionadas puedo combinar",
        "hay alguna tabla de soporte",
        "qué campos tiene campanias",
        "dime qué kpis están definidos",
        "cómo se relacionan ventas y clientes",
        "qué significa margen en el glosario",
        "muéstrame la metadata disponible",
        "qué fuentes de datos están conectadas",
        "explora los datos de web",
        "qué puedo preguntar",
    ],
    "comparacion": [
        "compara las ventas de 2024 contra 2025",
        "compara campañas por roi",
        "diferencia entre canal web y tienda",
        "cómo va este mes versus el mes anterior",
        "comparar margen por región",
        "qué región vende más que lima",
        "variación de ventas trimestre contra trimestre",
        "compara el desempeño de electrónica y moda",
        "crecimiento año contra año por categoría",
        "qué productos cayeron este trimestre",
        "qué categorías subieron respecto al periodo anterior",
        "contrasta el csat entre canales de contacto",
        "comparación de ticket promedio por segmento",
        "quién creció más, retail o corporativo",
        "evolución comparada de ingreso y margen",
        "vs el año pasado cómo vamos",
        # "qué X rindió mejor": comparación implícita, no exploración del catálogo
        "que campañas dieron mejor retorno",
        "que region vendio mas",
        "que producto se vendio mas",
        "que canal genera mas ingresos",
        "que categoria deja mas margen",
        "que clientes compran mas",
        "cuales campañas fueron mas rentables",
    ],
    "detalle": [
        "muéstrame las ventas del cliente 42",
        "dame el detalle de las transacciones de ayer",
        "quiero ver las filas de la tabla ventas",
        "lista los tickets abiertos",
        "detalle de pedidos de la campaña email",
        "muéstrame los registros con descuento mayor a 20%",
        "quiero el listado de clientes del segmento corporativo",
        "ver las últimas 50 ventas",
        "dame las ventas individuales de julio",
        "detalle por venta del producto 7",
        "muestra el desglose fila por fila",
        "quiero ver los datos crudos",
        "lista de sesiones web de ayer",
        "enséñame los registros de soporte escalados",
    ],
    "grafico": [
        "haz un gráfico de ventas por mes",
        "muéstrame un chart de ingresos",
        "grafica la evolución del margen",
        "dibuja un gráfico de barras por categoría",
        "quiero ver esto en un gráfico de líneas",
        "visualiza la tendencia de ventas",
        "muéstralo en un pastel por canal",
        "gráfico de top clientes",
        "plotea las ventas por región",
        "una visualización de la conversión web",
        "ponlo en un gráfico",
        "muéstrame la curva de ingresos mensuales",
        "gráfico comparativo de campañas",
        "diagrama de ventas por trimestre",
        "quiero un tablero visual de ventas",
        "muéstrame las ventas por mes y top clientes en gráfico",
    ],
    "exportacion": [
        "exporta el resultado a csv",
        "descarga la tabla en excel",
        "quiero bajar estos datos",
        "genera un archivo con las ventas",
        "exportar a csv por favor",
        "dame el csv de los top clientes",
        "necesito descargar el reporte",
        "puedes exportarme esta consulta",
        "guarda estos datos en un archivo",
        "envíame el archivo de resultados",
        "descárgame el detalle en csv",
        "exporta esto",
    ],
    "aclaracion": [
        "y eso",
        "no entiendo",
        "hola",
        "ayúdame",
        "qué opinas",
        "dame información",
        "algo más",
        "quiero datos",
        "muéstrame eso",
        "hazlo de nuevo pero mejor",
        "necesito un análisis",
        "puedes ayudarme con algo",
        "y lo otro",
        "revisa eso último",
        "no sé qué preguntar",
        "mmm",
        "ok",
        "sube el número",
        # Saludos y cortesía sin ninguna pregunta detrás
        "buenos días",
        "buenas tardes",
        "buenas noches",
        "qué tal",
        "hey",
        "gracias",
        "estás ahí",
        "necesito ayuda",
    ],
}

# Conjunto de evaluación independiente (usado por los tests)
EVALUACION: list[tuple[str, str]] = [
    ("muéstrame las ventas por mes", "KPI"),
    ("top 10 clientes por ingreso", "KPI"),
    ("compara campañas por roi", "comparacion"),
    ("qué productos cayeron este trimestre", "comparacion"),
    ("qué tablas no relacionadas puedo combinar", "exploracion"),
    ("hazme un gráfico de ventas por región", "grafico"),
    ("exporta el resultado a csv", "exportacion"),
    ("dame el detalle de las ventas de julio", "detalle"),
    ("hola", "aclaracion"),
    ("qué columnas tiene la tabla productos", "exploracion"),
    ("hola puedes decirme el meargen de categorias?", "KPI"),
    ("buenos días, dame el ingreso por región", "KPI"),
    ("porfavor muestrame el ticket promedio por canal", "KPI"),
    ("descarga estos datos en csv", "exportacion"),
    ("grafica la evolución del margen", "grafico"),
]
